source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

pod 'AFNetworking', '~> 2.4.0'
pod 'TTTAttributedLabel'
pod 'socket.IO'
pod 'TTTAttributedLabel'
pod 'MBProgressHUD'
pod 'AFNetworkActivityLogger'
pod 'RESideMenu'
pod 'SwipeView'
pod 'uservoice-iphone-sdk'
pod 'SLExpandableTableView'
pod 'XYPieChart'
