platform :ios, '7.0'
pod 'AFNetworking', '~> 2.0'
pod 'Nimbus'
pod 'socket.IO'
pod 'TTTAttributedLabel'
pod 'MBProgressHUD'
pod 'AFNetworkActivityLogger'
pod 'RESideMenu'
pod 'SwipeView'
pod 'uservoice-iphone-sdk'
